apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: nginx
    image: nginx:1.17-alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostame
            operator: In
            value:
            - worker1
            - worker2
     preferredDuringSchedulingIgnoreDuringExecution:
     - weight: 1
       preference:
         matchExpressions:
         - key: disktype
           operator: In
           value:
           - ssd
